Installs pipeline dependency packages
Specifically missing missing mysql dependencies when deploying analytics pipeline:

    TASK [analytics_pipeline : Grant access to table storing test data in output database] ******
    FAILED! => {"changed": false, "failed": true, "msg": "the python mysqldb module is required"}

But other packages are also required to install pipeline dependencies:

    Collecting psycopg2==2.6.2 (from -r requirements/default.txt (line 57))
        Error: pg_config executable not found.